// <auto-generated />
using AP.Demo_Project.Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AP.Demo_Project.Infrastructure.Migrations
{
    [DbContext(typeof(DemoContext))]
    partial class DemoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AP.Demo_Project.Domain.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)");

                    b.Property<long>("Population")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tblCities", "City");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            Name = "New York",
                            Population = 8419600L
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            Name = "Los Angeles",
                            Population = 3980400L
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 1,
                            Name = "Chicago",
                            Population = 2716000L
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 1,
                            Name = "Houston",
                            Population = 2328000L
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 1,
                            Name = "Phoenix",
                            Population = 1690000L
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 2,
                            Name = "London",
                            Population = 8982000L
                        },
                        new
                        {
                            Id = 7,
                            CountryId = 2,
                            Name = "Birmingham",
                            Population = 1141000L
                        },
                        new
                        {
                            Id = 8,
                            CountryId = 2,
                            Name = "Leeds",
                            Population = 789000L
                        },
                        new
                        {
                            Id = 9,
                            CountryId = 2,
                            Name = "Glasgow",
                            Population = 635000L
                        },
                        new
                        {
                            Id = 10,
                            CountryId = 2,
                            Name = "Sheffield",
                            Population = 584000L
                        });
                });

            modelBuilder.Entity("AP.Demo_Project.Domain.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tblCountries", "Country");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "United States"
                        },
                        new
                        {
                            Id = 2,
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = 4,
                            Name = "France"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Netherlands"
                        });
                });

            modelBuilder.Entity("AP.Demo_Project.Domain.City", b =>
                {
                    b.HasOne("AP.Demo_Project.Domain.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("AP.Demo_Project.Domain.Country", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
